# Generated by Django 3.1.7 on 2021-03-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0002_auto_20210328_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateTimeField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.home')),
            ],
        ),
        migrations.CreateModel(
            name='ListProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('R', 'Requested'), ('D', 'Done')], max_length=64)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.shoppinglist')),
            ],
        ),
    ]
