# Generated by Django 3.1.7 on 2021-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='completed_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
