# Generated by Django 3.1.7 on 2021-03-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_auto_20210330_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('D', 'Done')], default='R', max_length=64),
        ),
    ]
