# Generated by Django 3.1.7 on 2021-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0004_shoppinglist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproduct',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('D', 'Done')], default='R', max_length=64),
        ),
    ]
