# Generated by Django 3.1.7 on 2021-03-26 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('client', models.ManyToManyField(to='accounts.Client')),
                ('owners', models.ManyToManyField(related_name='owners', to='accounts.Client')),
            ],
        ),
        migrations.CreateModel(
            name='HomeInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_date', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.home')),
                ('invite_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('invite_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invited_client', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.home')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('name', 'home')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('new_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16, null=True)),
                ('unit', models.CharField(max_length=32)),
                ('stock', models.CharField(default='Full', max_length=64)),
                ('max_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
    ]
