# Generated by Django 3.1.7 on 2021-03-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_home'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeinvitation',
            unique_together={('home', 'invite_to')},
        ),
    ]
