# Generated by Django 3.1.1 on 2021-02-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'home')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
    ]
