# Generated by Django 3.1.1 on 2021-02-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210228_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stock_state',
        ),
    ]
