# Generated by Django 3.1.1 on 2021-02-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20210228_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.home'),
        ),
    ]
