# Generated by Django 3.1.1 on 2021-02-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_product_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='home',
        ),
    ]
